spring.application.name=backend

spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/musicLovers?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=a8f5f167f44f4964e6c998dee827110c5f3ed6b8c98f8e29b5c3e8a9f5d7e2b4
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG